#!/data/data/com.termux/files/usr/bin/bash

# Banner and center functions
center_banner() {
    local termwidth=$(stty size | cut -d" " -f2)

    local banner=(
        "=========================================="
        "           FNAI LINUX INSTALLER           "
        "=========================================="
        "======================="
        "       BY F0OLN3T      "
        "======================="
    )

    echo -e "\e[34m" # Blue color
    for line in "${banner[@]}"; do
        printf "%*s\n" $(( (termwidth + ${#line}) / 2 )) "$line"
    done
    echo -e "\e[0m" # Reset color
}

center_ban() {
    local term=$(stty size | cut -d" " -f2)

    local ban=(
        "========================="
        "   INSTALLER BY F0OLN3T  "
        "========================="
    )
    echo -e "\e[34m" # Blue color
    for line in "${ban[@]}"; do
        printf "%*s\n" $(( (term + ${#lin}) / 2 )) "$lin"
    done
    echo -e "\e[0m" # Reset color
}

clear
center_banner

# Loading spinner
echo -e "[FNAI] Loading..."
source <(echo "c3Bpbm5lcj0oICd8JyAnLycgJy0nICdcJyApOwoKY291bnQoKXsKICBzcGluICYKICBwaWQ9JCEKICBmb3IgaSBpbiBgc2VxIDEgMTBgCiAgZG8KICAgIHNsZWVwIDE7CiAgZG9uZQoKICBraWxsICRwaWQgIAp9CgpzcGluKCl7CiAgd2hpbGUgWyAxIF0KICBkbyAKICAgIGZvciBpIGluICR7c3Bpbm5lcltAXX07IAogICAgZG8gCiAgICAgIGVjaG8gLW5lICJcciRpIjsKICAgICAgc2xlZXAgMC4yOwogICAgZG9uZTsKICBkb25lCn0KCmNvdW50" | base64 -d)

echo -e ""
# Dependencies Installation (minimal)
echo -e "[FNAI] Instaling package..."
sudo apt update -y
sudo apt upgrade -y
sudo apt install python3 python3-pip
clear

source <(echo "c3Bpbm5lcj0oICd8JyAnLycgJy0nICdcJyApOwoKY291bnQoKXsKICBzcGluICYKICBwaWQ9JCEKICBmb3IgaSBpbiBgc2VxIDEgMTBgCiAgZG8KICAgIHNsZWVwIDE7CiAgZG9uZQoKICBraWxsICRwaWQgIAp9CgpzcGluKCl7CiAgd2hpbGUgWyAxIF0KICBkbyAKICAgIGZvciBpIGluICR7c3Bpbm5lcltAXX07IAogICAgZG8gCiAgICAgIGVjaG8gLW5lICJcciRpIjsKICAgICAgc2xlZXAgMC4yOwogICAgZG9uZTsKICBkb25lCn0KCmNvdW50" | base64 -d)

echo -e ""
echo -e "[FNAI] Instaling python package"
pip3 install base64
pip3 install google-genai
clear

echo -e "[FNAI] Instaling FNAi"
git clone https://github.com/f0oln3t/fnai
echo -e "\033[32m"
echo -e "Instaling complete, use 'cd fnai && python fnai.py' to run"
echo -e "\033[0m"
echo -e ""
center_ban
